### PR TITLE
Fix broken links and edits

### LINKED ISSUE #42: 404 Broken Link - Shared IP Resource
_From @trentgillaspie on August 12, 2016 4:59_

On https://developer.rackspace.com/docs/user-guides/orchestration/shared-ip/ , first link to http://docs-beta.rackspace.com/drafts/catlook/webhelp/cn-gettingstarted-external/content/share_ip.html results in a 404 Not Found. 

Where should it be pointing? Something like http://docs-beta.rackspace.com/drafts/catlook/webhelp/old-cn-devguide-external/content/api_ext_sharedip_neutron.html ? 

Thanks!

_Copied from original issue: rackerlabs/nexus-control#541_

### PR DESCRIPTION
**Pull request by meker12**
Fixes #42.
- Update shared IP links to point to recently published content
- Edits for clarity and style

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-74f82335cb/docs/user-guides/orchestration/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-aefb3d7730/docs/user-guides/orchestration/)

**Comment by meker12** [comment]
@rs-randallburt Can you or someone on your team review this PR to validate the changes?

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-4e72eabdb2/docs/user-guides/orchestration/). :bow:

**Pull request merged**
